"""Heading-aware chunking of rendered page HTML.

We work on the *rendered* HTML (`on_page_content`) rather than the Markdown source so that
heading anchors (`id` attributes generated by the `toc` extension) are known, which lets every
chunk carry a deep link (`page/#section`) for citations. This is the same approach the
built-in `search` plugin takes.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from html.parser import HTMLParser
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .config import ChunkingConfig

_HEADING_TAGS = frozenset(f"h{i}" for i in range(1, 7))
_SKIP_TAGS = frozenset({"script", "style", "noscript", "svg", "template"})
_BLOCK_TAGS = frozenset(
    {
        "p",
        "div",
        "li",
        "ul",
        "ol",
        "pre",
        "blockquote",
        "table",
        "thead",
        "tbody",
        "tr",
        "br",
        "hr",
        "section",
        "article",
        "dd",
        "dt",
        "dl",
        "figure",
        "figcaption",
        "details",
        "summary",
    }
)
_CELL_TAGS = frozenset({"td", "th"})

# Sentence boundaries: CJK terminators (U+3002 ideographic full stop, U+FF0E/FF01/FF1F
# fullwidth forms), ASCII '!'/'?', and '.' followed by whitespace.
_SENTENCE_SPLIT = re.compile("(?<=[\u3002\uff0e\uff01\uff1f!?])|(?<=\\.)\\s+")
_PARAGRAPH_SPLIT = re.compile(r"\n\s*\n")


@dataclass
class Chunk:
    url: str
    page_url: str
    page_title: str
    heading: str
    breadcrumbs: list[str]
    text: str

    def embedding_text(self, passage_prefix: str = "", include_breadcrumbs: bool = True) -> str:
        """Text fed to the embedding model (breadcrumbs add context to short chunks)."""
        if include_breadcrumbs and self.breadcrumbs:
            return f"{passage_prefix}{' > '.join(self.breadcrumbs)}\n{self.text}"
        return f"{passage_prefix}{self.text}"

    def to_json(self) -> dict[str, Any]:
        return {
            "url": self.url,
            "page_url": self.page_url,
            "page_title": self.page_title,
            "heading": self.heading,
            "breadcrumbs": self.breadcrumbs,
            "text": self.text,
        }


@dataclass
class _Section:
    level: int
    anchor: str | None
    title_parts: list[str] = field(default_factory=list)
    parts: list[tuple[str, bool]] = field(default_factory=list)  # (text, verbatim)

    @property
    def title(self) -> str:
        return _collapse_ws("".join(self.title_parts))

    def text(self) -> str:
        """Join fragments; prose whitespace is collapsed, <pre> fragments are kept verbatim."""
        out: list[str] = []
        prose: list[str] = []

        def flush() -> None:
            if not prose:
                return
            s = re.sub(r"[ \t\r\f\v\u00a0]+", " ", "".join(prose))
            s = re.sub(r" *\n *", "\n", s)
            out.append(s)
            prose.clear()

        for fragment, verbatim in self.parts:
            if verbatim:
                flush()
                out.append(fragment)
            else:
                prose.append(fragment)
        flush()
        raw = re.sub(r"\n{3,}", "\n\n", "".join(out))
        return raw.strip()


class _SectionParser(HTMLParser):
    """Group page text under the heading that precedes it."""

    def __init__(self, include_code: bool) -> None:
        super().__init__(convert_charrefs=True)
        self.include_code = include_code
        self.sections: list[_Section] = [_Section(level=0, anchor=None)]
        self._skip = 0
        self._pre = 0
        self._in_heading = False
        self._in_headerlink = False

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in _SKIP_TAGS:
            self._skip += 1
            return
        if self._skip:
            return
        attrs_d = dict(attrs)
        if tag in _HEADING_TAGS:
            self.sections.append(_Section(level=int(tag[1]), anchor=attrs_d.get("id")))
            self._in_heading = True
            return
        if self._in_heading:
            if tag == "a" and "headerlink" in (attrs_d.get("class") or ""):
                self._in_headerlink = True
            return
        if tag == "pre":
            self._pre += 1
        if tag in _BLOCK_TAGS:
            self._append("\n")
        elif tag in _CELL_TAGS:
            self._append(" ")

    def handle_endtag(self, tag: str) -> None:
        if tag in _SKIP_TAGS:
            self._skip = max(0, self._skip - 1)
            return
        if self._skip:
            return
        if tag in _HEADING_TAGS:
            self._in_heading = False
            self._in_headerlink = False
            return
        if self._in_heading:
            if tag == "a":
                self._in_headerlink = False
            return
        if tag == "pre":
            self._pre = max(0, self._pre - 1)
        if tag in _BLOCK_TAGS:
            self._append("\n")
        elif tag in _CELL_TAGS:
            self._append(" ")

    def handle_data(self, data: str) -> None:
        if self._skip:
            return
        if self._in_heading:
            if not self._in_headerlink:
                self.sections[-1].title_parts.append(data)
            return
        if self._pre:
            if self.include_code:
                self.sections[-1].parts.append((data, True))
            return
        self.sections[-1].parts.append((data, False))

    def _append(self, text: str) -> None:
        self.sections[-1].parts.append((text, False))


def _collapse_ws(text: str) -> str:
    return re.sub(r"\s+", " ", text.replace("\u00a0", " ")).strip()  # NBSP


def _split_units(text: str, limit: int) -> list[tuple[str, str]]:
    """Break text into (separator, unit) pairs no longer than `limit` characters."""
    units: list[tuple[str, str]] = []
    # `filter(None, ...)` rather than a `continue`: the only caller strips its input and the
    # separator's `\s*` is greedy, so two matches can never be adjacent and a blank paragraph
    # cannot actually occur. Guarding in one expression keeps that safety without leaving a
    # branch no test can reach.
    for para in filter(None, (p.strip() for p in _PARAGRAPH_SPLIT.split(text))):
        if len(para) <= limit:
            units.append(("\n\n", para))
            continue
        first = True
        for sent in _SENTENCE_SPLIT.split(para):
            sent = sent.strip()
            if not sent:
                continue
            sep = "\n\n" if first else " "
            first = False
            if len(sent) <= limit:
                units.append((sep, sent))
            else:
                for i in range(0, len(sent), limit):
                    units.append((sep if i == 0 else " ", sent[i : i + limit]))
    return units


def _overlap_tail(text: str, overlap: int) -> str:
    if overlap <= 0 or len(text) <= overlap:
        return ""
    tail = text[-overlap:]
    m = re.search(r"\s", tail)
    if m and m.end() < len(tail):
        tail = tail[m.end() :]
    return tail.strip()


def split_text(text: str, max_chars: int, overlap: int, min_chars: int) -> list[str]:
    """Pack paragraphs/sentences into chunks of at most `max_chars`, with `overlap` carry-over."""
    text = text.strip()
    if not text:
        return []
    if len(text) <= max_chars:
        return [text] if len(text) >= min_chars else []
    overlap = max(0, min(overlap, max_chars // 2))
    limit = max(max_chars - overlap - 1, 1)  # -1 for the joining separator
    chunks: list[str] = []
    buf = ""
    for sep, unit in _split_units(text, limit):
        if not buf:
            buf = unit
            continue
        if len(buf) + len(sep) + len(unit) <= max_chars:
            buf = f"{buf}{sep}{unit}"
            continue
        chunks.append(buf)
        tail = _overlap_tail(buf, overlap)
        buf = f"{tail}\n{unit}" if tail else unit
    # `buf` is always non-empty here, because this point is only reached for text longer
    # than max_chars and _split_units always yields at least one unit for non-empty text.
    # The guard stays as a safety net; "no branch" records that the false side is unreachable.
    if buf:  # pragma: no branch
        chunks.append(buf)
    return [c for c in chunks if len(c) >= min_chars]


def chunk_page(html: str, *, page_url: str, page_title: str, cfg: ChunkingConfig) -> list[Chunk]:
    """Turn one rendered page into citation-ready chunks."""
    parser = _SectionParser(include_code=cfg.include_code)
    parser.feed(html)
    parser.close()

    chunks: list[Chunk] = []
    stack: list[tuple[int, str]] = []
    for section in parser.sections:
        if section.level == 0:
            heading = page_title
            breadcrumbs = [page_title]
            anchor = None
        else:
            heading = section.title or page_title
            while stack and stack[-1][0] >= section.level:
                stack.pop()
            stack.append((section.level, heading))
            crumbs = [title for _, title in stack]
            breadcrumbs = crumbs if crumbs[0] == page_title else [page_title, *crumbs]
            anchor = section.anchor
        url = f"{page_url}#{anchor}" if anchor else page_url
        for piece in split_text(section.text(), cfg.max_chars, cfg.overlap, cfg.min_chars):
            chunks.append(
                Chunk(
                    url=url,
                    page_url=page_url,
                    page_title=page_title,
                    heading=heading,
                    breadcrumbs=list(breadcrumbs),
                    text=piece,
                )
            )
    return chunks
